"""Update Number

Revision ID: 8afd4deaae56
Revises: c917de4abc2c
Create Date: 2026-05-04 09:56:45.181578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afd4deaae56'
down_revision: Union[str, Sequence[str], None] = 'c917de4abc2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'number',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'number',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
